version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-service
    restart: always
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      USERNAME: postgres
      PASSWORD: 0zT7[C37x
    ports:
      - "80:8080"


  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0zT7[C37x
      PASSWORD_ENCODER_SECRET: ${PASSWORD_ENCODER_SECRET}
      PASSWORD_ITERATION: ${PASSWORD_ITERATION}
      PASSWORD_KEY_LENGTH: ${PASSWORD_KEY_LENGTH}
      JWT_ENCODER_SECRET: ${JWT_ENCODER_SECRET}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}
      TOKEN_ISSUER: ${TOKEN_ISSUER}
    env_file:
      - .env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
