version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-service
    restart: always
    depends_on:
      - db
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      USERNAME: postgres
      PASSWORD: 0zT7[C37x
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8080:8080"
      - "5005:5005"


  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0zT7[C37x
      PASSWORD_ENCODER_SECRET: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      PASSWORD_ITERATION: 64
      PASSWORD_KEY_LENGTH: 256
      JWT_ENCODER_SECRET: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
      REFRESH_TOKEN_EXPIRATION: 7
      ACCESS_TOKEN_EXPIRATION: 3600
      TOKEN_ISSUER: server
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
