spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  application:
    name: education
  datasource:
    url: ${DATASOURCE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-timeout: 30000

  flyway:
    enabled: true
    url: ${DATASOURCE_URL}
    user: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  password:
    encoder:
      secret: ${PASSWORD_ENCODER_SECRET:FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g}
      iteration: ${PASSWORD_ITERATION:64}
      keyLength: ${PASSWORD_KEY_LENGTH:256}
  secret:  ${JWT_ENCODER_SECRET:b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e}
  token:
    refresh:
      expiration: ${REFRESH_TOKEN_EXPIRATION:7}
    access:
      expiration: ${ACCESS_TOKEN_EXPIRATION:3600}
    issuer: ${TOKEN_ISSUER:server}

