spring:
  application:
    name: education
  datasource:
    url: ${DATASOURCE_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 600000

  flyway:
    enabled: true
    url: ${DATASOURCE_URL}
    user: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: false

jwt:
  password:
    encoder:
      secret: ${PASSWORD_ENCODER_SECRET:FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g}
      iteration: ${PASSWORD_ITERATION:64}
      keyLength: ${PASSWORD_KEY_LENGTH:256}
  secret:  ${JWT_ENCODER_SECRET:b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e}
  token:
    refresh:
      expiration: ${REFRESH_TOKEN_EXPIRATION:7}
    access:
      expiration: ${ACCESS_TOKEN_EXPIRATION:3600}
    issuer: ${TOKEN_ISSUER:server}

