CREATE TABLE register_user
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username               VARCHAR(255),
    password               VARCHAR(255),
    otp_code               VARCHAR(255),
    registration_try_count INTEGER,
    verified               BOOLEAN,
    otp_expiry_date        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_register_user PRIMARY KEY     (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255),
    password   VARCHAR(255),
    role       VARCHAR(255),
    enabled    BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);